### ISSUE TITLE
ohne plex pass

### ISSUE THREAD

**Issue by vr6syncro** [Eisbaeeer/ioBroker.plexconnect#5]
Ist der Adapter überhaupt in einer Form ohne Plex Pass nutzbar?
Adapter wird zwar grün aber es werden keine Objekte angelegt.

**Comment by Eisbaeeer** [comment]
Hallo erstmal
Derzeit unterstützt der Adapter nur Webhooks. Dieser dienst ist nur mit Plex Pass nutzbar. Der Adapter soll aber noch mit Diensten erweitert werden, für die kein Plex Pass nötig ist. Ist aber noch in Arbeit.

**Comment by vr6syncro** [comment]
Was bekommt man überhaupt an Daten ohne pass raus?

**Comment by Eisbaeeer** [comment]
Derzeit bekommt man ohne Plex Pass keine Daten zurückgemeldet, da Webhooks nur mit Plex Pass aktiviert werden kann.

**Comment by Eisbaeeer** [comment]
Ohne Plex-Pass gibt es gar keine Daten. No data without plex-pass. You will need plex-pass subscription to get this adapter working. Actually the adapter is on hold, because there is no new functionality from plex.
